# Generated by Django 5.2.7 on 2026-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_mark_existing_reports_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('seevcash', 'SeevCash'), ('subscription', 'Subscription renewal'), ('paystack', 'Paystack (legacy)'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
