# Generated by Django 5.2.17 on 2026-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordernotificationdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('seevcash', 'SeevCash'), ('subscription', 'Subscription renewal'), ('business_supply', 'Business supply renewal'), ('paystack', 'Paystack (legacy)'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20),
        ),
    ]
