# Generated by Django 5.2.17 on 2026-09-01 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_submission_report_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('other', 'Other')], default='motorbike', max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_phone_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_vehicle_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.driver'),
        ),
    ]
