# Generated by Django 5.2.7 on 2026-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_badge_region_alter_product_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Nutritional information e.g. Per 100g: Calories 350kcal, Protein 8g, Carbs 75g'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nutritional score out of 100'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_tips',
            field=models.TextField(blank=True, help_text='Storage and handling instructions e.g. Keep refrigerated, use within 7 days'),
        ),
    ]
