# Generated by Django 5.2.7 on 2026-06-07 08:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_nutritional_info_product_nutritional_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nutritional information e.g. Per 100g: Calories 350kcal, Protein 8g, Carbs 75g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_tips',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Storage and handling instructions e.g. Keep refrigerated, use within 7 days'),
        ),
    ]
