# Generated by Django 5.2.17 on 2026-08-27 21:43

from django.db import migrations, models
from django.db.models import Q


def classify_existing_business_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(
        Q(name__icontains='tomato') | Q(slug__icontains='tomato')
    ).update(business_supply_category='tomato')
    Product.objects.filter(
        Q(name__icontains='onion') | Q(slug__icontains='onion')
    ).update(business_supply_category='onion')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_supply_category',
            field=models.CharField(blank=True, choices=[('tomato', 'Tomatoes'), ('onion', 'Onions')], help_text='Set only for products available through the B2B tomato and onion catalogue.', max_length=20),
        ),
        migrations.RunPython(classify_existing_business_products, migrations.RunPython.noop),
    ]
