# Generated by Django 5.2.7 on 2026-08-08 07:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_mark_existing_reports_historical'),
        ('products', '0005_productimage'),
        ('users', '0010_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('delivery_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('cutoff_hours', models.PositiveSmallIntegerField(default=48)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('audience', models.CharField(choices=[('household', 'Household'), ('business', 'Business')], default='household', max_length=20)),
                ('plan_type', models.CharField(choices=[('curated', 'Curated'), ('custom', 'Build your week')], default='curated', max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=180)),
                ('weekly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('household_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/plans/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'weekly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('audience', models.CharField(choices=[('household', 'Household'), ('business', 'Business')], default='household', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending payment'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('delivery_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('weekly_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, editable=False, max_length=100)),
                ('paystack_authorization_code', models.CharField(blank=True, editable=False, max_length=150)),
                ('payment_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('card_brand', models.CharField(blank=True, editable=False, max_length=40)),
                ('card_last4', models.CharField(blank=True, editable=False, max_length=4)),
                ('authorization_reusable', models.BooleanField(default=False, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.b2bprofile')),
                ('delivery_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.deliveryzone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted to order')], default='draft', max_length=20)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('customer_note', models.TextField(blank=True)),
                ('staff_note', models.TextField(blank=True)),
                ('quoted_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='users.b2bprofile')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('requested_unit', models.CharField(blank=True, max_length=80)),
                ('quoted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.wholesalequote')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('can_substitute', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='products.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'product'), name='unique_product_per_subscription')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('can_swap', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptionplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_items', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'product'), name='unique_product_per_subscription_plan')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('cutoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('skipped', 'Skipped'), ('packing', 'Packing'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('payment_failed', 'Payment failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_attempts', models.PositiveSmallIntegerField(default=0)),
                ('payment_error', models.CharField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_week', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeks', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['delivery_date'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'delivery_date'), name='unique_subscription_delivery_week')],
            },
        ),
    ]
