# Generated by Django 5.2.7 on 2026-08-18 08:27

from django.db import migrations, models


def migrate_payment_states(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    SubscriptionWeek = apps.get_model('subscriptions', 'SubscriptionWeek')
    Subscription.objects.filter(status='pending_payment').update(status='draft')
    SubscriptionWeek.objects.filter(status='payment_pending').update(status='payment_due')


def reverse_payment_states(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    SubscriptionWeek = apps.get_model('subscriptions', 'SubscriptionWeek')
    Subscription.objects.filter(status='draft').update(status='pending_payment')
    SubscriptionWeek.objects.filter(status='payment_due').update(status='payment_pending')


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_delivery_zones'),
    ]

    operations = [
        migrations.RunPython(migrate_payment_states, reverse_payment_states),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionweek',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('renewal_order', 'Renewal order'), ('payment_due', 'Payment due'), ('paid', 'Paid'), ('skipped', 'Skipped'), ('packing', 'Packing'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
    ]
