# Generated by Django 5.2.7 on 2026-08-20 19:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.CharField(max_length=300)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('recipients_prepared_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_subscription_price_changes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPriceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_id', models.CharField(blank=True, editable=False, max_length=160)),
                ('attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('last_error', models.CharField(blank=True, editable=False, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_change', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='subscriptions.subscriptionplanpricechange')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_notices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanpricechange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('plan',), name='one_scheduled_price_change_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpricenotice',
            constraint=models.UniqueConstraint(fields=('price_change', 'subscription'), name='one_notice_per_price_change_subscription'),
        ),
    ]
