# Generated by Django 5.2.17 on 2026-08-23 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordernotificationdelivery'),
        ('products', '0005_productimage'),
        ('subscriptions', '0004_subscriptionplanpricechange_subscriptionpricenotice_and_more'),
        ('users', '0013_b2bprofile_assigned_to_alter_b2bprofile_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSupplyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly')], max_length=20)),
                ('delivery_address', models.TextField()),
                ('receiving_contact_name', models.CharField(max_length=150)),
                ('receiving_contact_phone', models.CharField(max_length=20)),
                ('receiving_hours', models.CharField(blank=True, max_length=200)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_agreements', to='users.b2bprofile')),
                ('delivery_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_supply_agreements', to='subscriptions.deliveryzone')),
                ('legacy_subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_business_supply', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSupplyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('customer_note', models.TextField(blank=True)),
                ('staff_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='subscriptions.businesssupplyagreement')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_supply_revisions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_business_supply_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSupplyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('payment_due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('renewal_order', 'Renewal order'), ('payment_due', 'Payment due'), ('paid', 'Paid'), ('skipped', 'Skipped'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('packing', 'Packing'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='renewal_order', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_attempts', models.PositiveSmallIntegerField(default=0)),
                ('payment_error', models.CharField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='subscriptions.businesssupplyagreement')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_supply_cycle', to='orders.order')),
            ],
            options={
                'ordering': ['delivery_date'],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'delivery_date'), name='unique_business_supply_delivery_cycle')],
            },
        ),
        migrations.CreateModel(
            name='BusinessSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('can_substitute', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.businesssupplyagreement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_supply_items', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'product'), name='unique_product_per_business_supply')],
            },
        ),
    ]
