# Generated by Django 5.2.17 on 2026-08-23 07:10

from django.db import migrations


def migrate_business_subscriptions(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    Agreement = apps.get_model('subscriptions', 'BusinessSupplyAgreement')
    SupplyItem = apps.get_model('subscriptions', 'BusinessSupplyItem')
    SupplyCycle = apps.get_model('subscriptions', 'BusinessSupplyCycle')

    status_map = {
        'draft': 'draft', 'active': 'active',
        'paused': 'paused', 'cancelled': 'cancelled',
    }
    cycle_statuses = {
        'scheduled': 'renewal_order', 'renewal_order': 'renewal_order',
        'payment_due': 'payment_due', 'paid': 'paid', 'skipped': 'skipped',
        'payment_failed': 'payment_failed', 'expired': 'expired',
        'cancelled': 'cancelled', 'packing': 'packing',
        'out_for_delivery': 'out_for_delivery', 'delivered': 'delivered',
    }
    for subscription in Subscription.objects.filter(
        audience='business', business_profile__isnull=False
    ).iterator():
        agreement, _ = Agreement.objects.get_or_create(
            legacy_subscription=subscription,
            defaults={
                'business_id': subscription.business_profile_id,
                'name': subscription.name or 'Business supply',
                'status': status_map.get(subscription.status, 'draft'),
                'frequency': 'weekly',
                'delivery_zone_id': subscription.delivery_zone_id,
                'delivery_address': subscription.delivery_address,
                'receiving_contact_name': subscription.user.get_full_name() or subscription.user.email,
                'receiving_contact_phone': subscription.contact_phone,
                'subtotal': subscription.weekly_subtotal,
                'delivery_fee': subscription.weekly_delivery_fee,
                'next_delivery_date': subscription.next_delivery_date,
                'activated_at': subscription.started_at,
                'paused_at': subscription.paused_at,
                'cancelled_at': subscription.cancelled_at,
            },
        )
        for item in subscription.items.all():
            SupplyItem.objects.get_or_create(
                agreement=agreement, product_id=item.product_id,
                defaults={
                    'quantity': item.quantity, 'unit_price': item.unit_price,
                    'can_substitute': item.can_substitute,
                    'display_order': item.display_order,
                },
            )
        for week in subscription.weeks.all():
            SupplyCycle.objects.get_or_create(
                agreement=agreement, delivery_date=week.delivery_date,
                defaults={
                    'payment_due_at': week.cutoff_at,
                    'status': cycle_statuses.get(week.status, 'renewal_order'),
                    'subtotal': week.subtotal, 'delivery_fee': week.delivery_fee,
                    'payment_reference': week.payment_reference or '',
                    'payment_attempts': week.payment_attempts,
                    'payment_error': week.payment_error,
                    'paid_at': week.paid_at, 'order_id': week.order_id,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_business_supply_domain'),
    ]

    operations = [
        migrations.RunPython(migrate_business_subscriptions, migrations.RunPython.noop),
    ]
