# Generated by Django 5.2.6 on 2025-09-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packing_sizes', models.JSONField(blank=True, null=True)),
                ('farming_method', models.CharField(choices=[('organic', 'Organic'), ('conventional', 'Conventional'), ('integrated', 'Integrated')], default='organic', max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.farm')),
            ],
        ),
    ]
