"""
Django settings for legitorganic project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import resend
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from django.templatetags.static import static


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default='False'):
    """Parse a boolean env var robustly. Absent → the given default (itself
    parsed), so an unset DEBUG resolves to False rather than True."""
    return os.getenv(name, default).strip().lower() in ('true', '1', 'yes', 'on')


def production_security_settings(debug):
    """Security settings applied only when NOT in debug mode. Returned as a dict
    (instead of assigned inline) so both modes are directly unit-testable. In
    debug mode the empty dict leaves Django's dev-friendly defaults in place."""
    if debug:
        return {}
    return {
        'SESSION_COOKIE_SECURE': True,
        'CSRF_COOKIE_SECURE': True,
        'SECURE_SSL_REDIRECT': True,
        'SECURE_HSTS_SECONDS': 31536000,
        'SECURE_HSTS_INCLUDE_SUBDOMAINS': True,
        'SECURE_HSTS_PRELOAD': False,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-insecure-key')

RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
resend.api_key = RESEND_API_KEY
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'hello@legitorganic.com')
ORDER_REPORT_EMAIL = os.getenv('ORDER_REPORT_EMAIL', 'legitorganic9@gmail.com')
ORDER_REPORT_MAX_ATTEMPTS = int(os.getenv('ORDER_REPORT_MAX_ATTEMPTS', '10'))
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://legitorganic.com')
DASHBOARD_URL = os.getenv('DASHBOARD_URL', 'https://dashboard.legitorganic.com')
LOGIN_REDIRECT_URL = '/admin/'
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
# Currency Paystack transactions are expected to settle in (ISO 4217).
PAYSTACK_CURRENCY = os.getenv('PAYSTACK_CURRENCY', 'GHS')

# SeevCash Checkout API. Keep the checkout secret server-side; the public key is
# retained for future provider widgets but is not required by the hosted REST flow.
SEEVCASH_PUBLIC_KEY = os.getenv('SEEVCASH_PUBLIC_KEY', '')
SEEVCASH_SECRET_KEY = os.getenv(
    'SEEVCASH_SECRET_KEY', os.getenv('SEEV_CHECKOUT_API_KEY', '')
)
SEEVCASH_CURRENCY = os.getenv('SEEVCASH_CURRENCY', 'GHS')
SEEVCASH_BASE_URL = os.getenv('SEEVCASH_BASE_URL', 'https://api.seevplus.com').rstrip('/')
SEEVCASH_TIMEOUT = int(os.getenv('SEEVCASH_TIMEOUT', '15'))
SEEVCASH_WEBHOOK_SECRET = os.getenv(
    'SEEVCASH_WEBHOOK_SECRET', os.getenv('SEEV_WEBHOOK_SECRET', '')
)

# Cloudflare Turnstile — configurable, and OFF until a secret key is provisioned.
# With no key set (current dev + production), registration is unaffected.
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
TURNSTILE_ENABLED = os.getenv('TURNSTILE_ENABLED', 'true').lower() == 'true' and bool(TURNSTILE_SECRET_KEY)

# Email-verification token lifetime (hours). email_verification_sent_at is enforced
# against this in VerifyEmailView.
EMAIL_VERIFICATION_TOKEN_HOURS = int(os.getenv('EMAIL_VERIFICATION_TOKEN_HOURS', '24'))
GUEST_ORDER_TOKEN_MAX_AGE = int(os.getenv('GUEST_ORDER_TOKEN_MAX_AGE', '604800'))
WIGAL_API_KEY = os.getenv('WIGAL_API_KEY', '')
WIGAL_SENDER_ID = os.getenv('WIGAL_SENDER_ID', 'LegitGH')
WIGAL_USERNAME = os.getenv('WIGAL_USERNAME', '')

# SECURITY WARNING: don't run with debug turned on in production!
# Production-safe: an unset DEBUG resolves to False.
DEBUG = _env_bool("DEBUG", "False")

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'https://legitorganic.com').split(',')
    if o.strip()
]

# Production security hardening — applied only when DEBUG is False. nginx
# terminates TLS and forwards X-Forwarded-Proto, and SECURE_PROXY_SSL_HEADER
# (above) makes Django trust it, so Secure cookies + SSL redirect work without
# redirect loops. In DEBUG (local dev over http) none of these apply, which
# preserves development usability.
globals().update(production_security_settings(DEBUG))

# The CSRF token cookie must stay readable by frontend JavaScript, so it is
# never marked HttpOnly (in either mode).
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    # third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # unfold (must come before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    # ckeditor
    'django_ckeditor_5',
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'axes',
    # local
    'users',
    'products',
    'blog',
    'recipes',
    'orders',
    'sales',
    'notifications',
    'subscriptions.apps.SubscriptionsConfig',
    'security.apps.SecurityConfig',
]

def admin_permission(permission):
    return lambda request: request.user.has_perm(permission)


def staff_access(request):
    return request.user.is_authenticated and request.user.is_staff


UNFOLD = {
    "SITE_TITLE": "Legit Organic Control Room",
    "SITE_HEADER": "Legit Organic",
    "SITE_URL": "https://legitorganic.com",
    "SITE_ICON": "https://legitorganic.com/images/logo-darkmode.svg",
    "SITE_LOGO": "https://legitorganic.com/images/logo-darkmode.svg",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "type": "image/svg+xml",
            "href": "https://legitorganic.com/icon.svg",
        },
    ],
    "SITE_SYMBOL": "eco",
    "DASHBOARD_CALLBACK": "legitorganic.dashboard.dashboard_callback",
    "STYLES": [
        lambda request: f'{static("admin/css/legitorganic-admin.css")}?v=20260822-1',
    ],
    "SCRIPTS": [
        lambda request: static("admin/js/legitorganic-admin.js"),
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "130 198 138",
            "500": "76 153 80",
            "600": "46 125 50",
            "700": "26 91 53",
            "800": "13 59 42",
            "900": "10 45 32",
            "950": "5 25 18",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Catalogue & Stories",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "shopping_basket",
                        "link": "/admin/products/product/",
                        "permission": admin_permission("products.view_product"),
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/products/category/",
                        "permission": admin_permission("products.view_category"),
                    },
                    {
                        "title": "Regions",
                        "icon": "location_on",
                        "link": "/admin/products/region/",
                        "permission": admin_permission("products.view_region"),
                    },
                    {
                        "title": "Badges",
                        "icon": "label",
                        "link": "/admin/products/badge/",
                        "permission": admin_permission("products.view_badge"),
                    },
                    {
                        "title": "Journal Posts",
                        "icon": "article",
                        "link": "/admin/blog/blogpost/",
                        "permission": admin_permission("blog.view_blogpost"),
                    },
                    {
                        "title": "Journal Categories",
                        "icon": "folder",
                        "link": "/admin/blog/blogcategory/",
                        "permission": admin_permission("blog.view_blogcategory"),
                    },
                    {
                        "title": "Recipes",
                        "icon": "restaurant_menu",
                        "link": "/admin/recipes/recipe/",
                        "permission": admin_permission("recipes.view_recipe"),
                    },
                ],
            },
            {
                "title": "Commerce",
                "separator": True,
                "items": [
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": "/admin/orders/order/",
                        "permission": admin_permission("orders.view_order"),
                    },
                    {
                        "title": "Carts",
                        "icon": "shopping_cart",
                        "link": "/admin/orders/cart/",
                        "permission": admin_permission("orders.view_cart"),
                    },
                    {
                        "title": "Promo Codes",
                        "icon": "local_offer",
                        "link": "/admin/orders/promocode/",
                        "permission": admin_permission("orders.view_promocode"),
                    },
                ],
            },
            {
                "title": "Weekly Delivery",
                "separator": True,
                "items": [
                    {
                        "title": "Plans",
                        "icon": "inventory_2",
                        "link": "/admin/subscriptions/subscriptionplan/",
                        "permission": admin_permission("subscriptions.view_subscriptionplan"),
                    },
                    {
                        "title": "Scheduled pricing",
                        "icon": "calendar_clock",
                        "link": "/admin/subscriptions/subscriptionplanpricechange/",
                        "permission": admin_permission("subscriptions.view_subscriptionplanpricechange"),
                    },
                    {
                        "title": "Price notices",
                        "icon": "mark_email_read",
                        "link": "/admin/subscriptions/subscriptionpricenotice/",
                        "permission": admin_permission("subscriptions.view_subscriptionpricenotice"),
                    },
                    {
                        "title": "Subscribers",
                        "icon": "event_repeat",
                        "link": "/admin/subscriptions/subscription/",
                        "permission": admin_permission("subscriptions.view_subscription"),
                    },
                    {
                        "title": "Weekly deliveries",
                        "icon": "local_shipping",
                        "link": "/admin/subscriptions/subscriptionweek/",
                        "permission": admin_permission("subscriptions.view_subscriptionweek"),
                    },
                    {
                        "title": "Delivery zones",
                        "icon": "map",
                        "link": "/admin/subscriptions/deliveryzone/",
                        "permission": admin_permission("subscriptions.view_deliveryzone"),
                    },
                ],
            },
            {
                "title": "Customers",
                "separator": True,
                "items": [
                    {
                        "title": "Customers",
                        "icon": "person",
                        "link": "/admin/users/customer/",
                        "permission": admin_permission("users.view_customer"),
                    },
                ],
            },
            {
                "title": "Staff",
                "separator": True,
                "items": [
                    {
                        "title": "My account security",
                        "icon": "shield_lock",
                        "link": "/staff/security/setup/",
                        "permission": staff_access,
                    },
                    {
                        "title": "Security audit",
                        "icon": "policy",
                        "link": "/admin/security/auditevent/",
                        "permission": staff_access,
                    },
                    {
                        "title": "Staff Accounts",
                        "icon": "badge",
                        "link": "/admin/users/staff/",
                        "permission": admin_permission("users.view_staff"),
                    },
                    {
                        "title": "Staff Invitations",
                        "icon": "forward_to_inbox",
                        "link": "/admin/users/staffinvitation/",
                        "permission": admin_permission("users.view_staffinvitation"),
                    },
                ],
            },
            {
                "title": "Wholesale",
                "separator": True,
                "items": [
                    {
                        "title": "B2B Applications",
                        "icon": "business",
                        "link": "/admin/users/b2bprofile/",
                        "permission": admin_permission("users.view_b2bprofile"),
                    },
                    {
                        "title": "B2B Review History",
                        "icon": "history",
                        "link": "/admin/users/b2breviewevent/",
                        "permission": admin_permission("users.view_b2breviewevent"),
                    },
                    {
                        "title": "Business Prices",
                        "icon": "price_change",
                        "link": "/admin/users/businesspricelist/",
                        "permission": admin_permission("users.view_businesspricelist"),
                    },
                    {
                        "title": "Wholesale Quotes",
                        "icon": "request_quote",
                        "link": "/admin/subscriptions/wholesalequote/",
                        "permission": admin_permission("subscriptions.view_wholesalequote"),
                    },
                ],
            },
            {
                "title": "Sales Team",
                "separator": True,
                "items": [
                    {
                        "title": "Sales Reps",
                        "icon": "badge",
                        "link": "/admin/sales/salesrep/",
                        "permission": admin_permission("sales.view_salesrep"),
                    },
                    {
                        "title": "Referred Customers",
                        "icon": "group_add",
                        "link": "/admin/sales/referredcustomer/",
                        "permission": admin_permission("sales.view_referredcustomer"),
                    },
                    {
                        "title": "Commissions",
                        "icon": "payments",
                        "link": "/admin/sales/commission/",
                        "permission": admin_permission("sales.view_commission"),
                    },
                ],
            },
            {
                "title": "Useful Links",
                "separator": True,
                "items": [
                    {
                        "title": "Visit Live Site",
                        "icon": "open_in_new",
                        "link": "https://legitorganic.com",
                        "target": "_blank",
                    },
                    {
                        "title": "View Products",
                        "icon": "storefront",
                        "link": "https://legitorganic.com/products",
                        "target": "_blank",
                    },
                    {
                        "title": "View Journal",
                        "icon": "article",
                        "link": "https://legitorganic.com/blog",
                        "target": "_blank",
                    },
                    {
                        "title": "View Recipes",
                        "icon": "restaurant_menu",
                        "link": "https://legitorganic.com/recipes",
                        "target": "_blank",
                    },
                    {
                        "title": "Wigal SMS Dashboard",
                        "icon": "sms",
                        "link": "https://frog.wigal.com.gh/dashboard",
                        "target": "_blank",
                    },
                ],
            },
        ],
    },
}

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', '|',
                'bulletedList', 'numberedList', '|',
                'blockQuote', '|',
                'link', '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True,
            }
        },
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', '|',
                'bulletedList', 'numberedList', '|',
                'outdent', 'indent', '|',
                'blockQuote', '|',
                'link', '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
    },
}

CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Deploy in enrollment mode first. Switch to "enforce" only after the owner
# has enrolled and safely stored the recovery codes.
STAFF_2FA_MODE = os.getenv('STAFF_2FA_MODE', 'enroll').strip().lower()
if STAFF_2FA_MODE not in {'enroll', 'enforce'}:
    raise ImproperlyConfigured('STAFF_2FA_MODE must be either "enroll" or "enforce".')
STAFF_OWNER_2FA_REQUIRED = _env_bool('STAFF_OWNER_2FA_REQUIRED', 'True')
STAFF_IDLE_TIMEOUT_SECONDS = int(os.getenv('STAFF_IDLE_TIMEOUT_SECONDS', '1800'))
STAFF_ABSOLUTE_SESSION_SECONDS = int(os.getenv('STAFF_ABSOLUTE_SESSION_SECONDS', '28800'))
OTP_TOTP_ISSUER = os.getenv('OTP_TOTP_ISSUER', 'LegitOrganic.com').strip()

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # hours (15 minutes)
AXES_RESET_ON_SUCCESS = True
# Lock the account and the source IP independently. A nested pair would only
# lock the exact username+IP combination and lets distributed attacks continue.
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_IPWARE_PROXY_COUNT = 1
AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'axes.middleware.AxesMiddleware',
    'security.middleware.StaffSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:4200,http://127.0.0.1:4200"
    ).split(",")
]
CORS_ALLOW_CREDENTIALS = True

SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


ROOT_URLCONF = 'legitorganic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'legitorganic.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CustomerJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    # ScopedRateThrottle only throttles views that declare `throttle_scope`, so
    # everything else is unaffected. Defense-in-depth: the observed bot campaign
    # used ~1 IP per request, so these per-IP limits are one layer, not the whole
    # defense (Turnstile is the other).
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    # Exactly one trusted proxy hop (Nginx). DRF derives the throttle identity from
    # the LAST X-Forwarded-For entry (the address Nginx observed), so a client
    # cannot mint fresh identities by spoofing the first X-Forwarded-For value.
    "NUM_PROXIES": 1,
    "DEFAULT_THROTTLE_RATES": {
        "register": "5/hour",
        "login": "10/min",
        "google_auth": "10/min",
        "token_refresh": "30/min",
        "password_setup": "5/hour",
        "payment_initialize": "10/min",
        "payment_verify": "20/min",
        "payment_webhook": "120/min",
        "public_lookup": "30/min",
        "resend_verification": "3/hour",
        "recipe_note": "20/hour",
        "b2b_apply": "5/hour",
        "guest_order": "20/hour",
        "promo_validate": "30/hour",
    },
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'legitorganic'),
        'USER': os.getenv('DB_USER', 'legitorganic_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_B2B_ROOT = Path(
    os.environ.get('PRIVATE_B2B_ROOT', BASE_DIR / 'private_media' / 'b2b')
)

# USDA FoodData Central is queried server-side. Never expose this key to the browser.
USDA_FDC_API_KEY = os.getenv('USDA_FDC_API_KEY', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google OAuth
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

LOG_FILE = os.environ.get(
    'DJANGO_LOG_FILE',
    os.path.join(BASE_DIR, 'django_errors.log')
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
