"""
Django settings for legitorganic project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import resend
from dotenv import load_dotenv
from django.templatetags.static import static


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default='False'):
    """Parse a boolean env var robustly. Absent → the given default (itself
    parsed), so an unset DEBUG resolves to False rather than True."""
    return os.getenv(name, default).strip().lower() in ('true', '1', 'yes', 'on')


def production_security_settings(debug):
    """Security settings applied only when NOT in debug mode. Returned as a dict
    (instead of assigned inline) so both modes are directly unit-testable. In
    debug mode the empty dict leaves Django's dev-friendly defaults in place."""
    if debug:
        return {}
    return {
        'SESSION_COOKIE_SECURE': True,
        'CSRF_COOKIE_SECURE': True,
        'SECURE_SSL_REDIRECT': True,
        'SECURE_HSTS_SECONDS': 300,
        'SECURE_HSTS_INCLUDE_SUBDOMAINS': False,
        'SECURE_HSTS_PRELOAD': False,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-insecure-key')

RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
resend.api_key = RESEND_API_KEY
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'hello@legitorganic.com')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://legitorganic.com')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
# Currency Paystack transactions are expected to settle in (ISO 4217).
PAYSTACK_CURRENCY = os.getenv('PAYSTACK_CURRENCY', 'GHS')

# Cloudflare Turnstile — configurable, and OFF until a secret key is provisioned.
# With no key set (current dev + production), registration is unaffected.
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
TURNSTILE_ENABLED = os.getenv('TURNSTILE_ENABLED', 'true').lower() == 'true' and bool(TURNSTILE_SECRET_KEY)

# Email-verification token lifetime (hours). email_verification_sent_at is enforced
# against this in VerifyEmailView.
EMAIL_VERIFICATION_TOKEN_HOURS = int(os.getenv('EMAIL_VERIFICATION_TOKEN_HOURS', '24'))
WIGAL_API_KEY = os.getenv('WIGAL_API_KEY', '')
WIGAL_SENDER_ID = os.getenv('WIGAL_SENDER_ID', 'LegitGH')
WIGAL_USERNAME = os.getenv('WIGAL_USERNAME', '')

# SECURITY WARNING: don't run with debug turned on in production!
# Production-safe: an unset DEBUG resolves to False.
DEBUG = _env_bool("DEBUG", "False")

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'https://legitorganic.com').split(',')
    if o.strip()
]

# Production security hardening — applied only when DEBUG is False. nginx
# terminates TLS and forwards X-Forwarded-Proto, and SECURE_PROXY_SSL_HEADER
# (above) makes Django trust it, so Secure cookies + SSL redirect work without
# redirect loops. In DEBUG (local dev over http) none of these apply, which
# preserves development usability.
globals().update(production_security_settings(DEBUG))

# The CSRF token cookie must stay readable by frontend JavaScript, so it is
# never marked HttpOnly (in either mode).
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    # third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # unfold (must come before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    # ckeditor
    'django_ckeditor_5',
    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local
    'users',
    'products',
    'blog',
    'recipes',
    'orders',
    'sales',
    'notifications',
]

UNFOLD = {
    "SITE_TITLE": "Legit Organic",
    "SITE_HEADER": "Legit Organic Admin",
    "SITE_URL": "https://legitorganic.com",
    "SITE_ICON": lambda request: static("images/logo-lightmode.svg"),
    "SITE_LOGO": lambda request: static("images/logo-lightmode.svg"),
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "type": "image/svg+xml",
            "href": lambda request: static("images/logo-lightmode.svg"),
        },
    ],
    "SITE_SYMBOL": "eco",
    "DASHBOARD_CALLBACK": "legitorganic.dashboard.dashboard_callback",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "auto",
    "COLORS": {
        "primary": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "34 197 94",
            "600": "22 163 74",
            "700": "15 118 52",
            "800": "13 59 42",
            "900": "10 45 32",
            "950": "5 25 18",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Content",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "shopping_basket",
                        "link": "/admin/products/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/products/category/",
                    },
                    {
                        "title": "Regions",
                        "icon": "location_on",
                        "link": "/admin/products/region/",
                    },
                    {
                        "title": "Badges",
                        "icon": "label",
                        "link": "/admin/products/badge/",
                    },
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": "/admin/blog/blogpost/",
                    },
                    {
                        "title": "Blog Categories",
                        "icon": "folder",
                        "link": "/admin/blog/blogcategory/",
                    },
                    {
                        "title": "Recipes",
                        "icon": "restaurant_menu",
                        "link": "/admin/recipes/recipe/",
                    },
                ],
            },
            {
                "title": "Orders",
                "separator": True,
                "items": [
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": "/admin/orders/order/",
                    },
                    {
                        "title": "Carts",
                        "icon": "shopping_cart",
                        "link": "/admin/orders/cart/",
                    },
                    {
                        "title": "Promo Codes",
                        "icon": "local_offer",
                        "link": "/admin/orders/promocode/",
                    },
                ],
            },
            {
                "title": "Users",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/users/user/",
                    },
                    {
                        "title": "Customers",
                        "icon": "person",
                        "link": "/admin/users/customer/",
                    },
                ],
            },
            {
                "title": "B2B Portal",
                "separator": True,
                "items": [
                    {
                        "title": "B2B Applications",
                        "icon": "business",
                        "link": "/admin/users/b2bprofile/",
                    },
                    {
                        "title": "Discount Tiers",
                        "icon": "percent",
                        "link": "/admin/users/b2bdiscounttier/",
                    },
                ],
            },
            {
                "title": "Sales Reps",
                "separator": True,
                "items": [
                    {
                        "title": "Sales Reps",
                        "icon": "badge",
                        "link": "/admin/sales/salesrep/",
                    },
                    {
                        "title": "Referred Customers",
                        "icon": "group_add",
                        "link": "/admin/sales/referredcustomer/",
                    },
                    {
                        "title": "Commissions",
                        "icon": "payments",
                        "link": "/admin/sales/commission/",
                    },
                ],
            },
            {
                "title": "Website",
                "separator": True,
                "items": [
                    {
                        "title": "Visit Live Site",
                        "icon": "open_in_new",
                        "link": "https://legitorganic.com",
                        "target": "_blank",
                    },
                    {
                        "title": "View Products",
                        "icon": "storefront",
                        "link": "https://legitorganic.com/products",
                        "target": "_blank",
                    },
                    {
                        "title": "View Blog",
                        "icon": "article",
                        "link": "https://legitorganic.com/blog",
                        "target": "_blank",
                    },
                    {
                        "title": "View Recipes",
                        "icon": "restaurant_menu",
                        "link": "https://legitorganic.com/recipes",
                        "target": "_blank",
                    },
                    {
                        "title": "Wigal SMS Dashboard",
                        "icon": "sms",
                        "link": "https://frog.wigal.com.gh/dashboard",
                        "target": "_blank",
                    },
                ],
            },
        ],
    },
}

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', '|',
                'bulletedList', 'numberedList', '|',
                'blockQuote', '|',
                'link', '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True,
            }
        },
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', '|',
                'bulletedList', 'numberedList', '|',
                'outdent', 'indent', '|',
                'blockQuote', '|',
                'link', '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
    },
}

CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:4200,http://127.0.0.1:4200"
    ).split(",")
]


ROOT_URLCONF = 'legitorganic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'legitorganic.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    # ScopedRateThrottle only throttles views that declare `throttle_scope`, so
    # everything else is unaffected. Defense-in-depth: the observed bot campaign
    # used ~1 IP per request, so these per-IP limits are one layer, not the whole
    # defense (Turnstile is the other).
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    # Exactly one trusted proxy hop (Nginx). DRF derives the throttle identity from
    # the LAST X-Forwarded-For entry (the address Nginx observed), so a client
    # cannot mint fresh identities by spoofing the first X-Forwarded-For value.
    "NUM_PROXIES": 1,
    "DEFAULT_THROTTLE_RATES": {
        "register": "5/hour",
        "login": "10/min",
        "resend_verification": "3/hour",
        "recipe_note": "20/hour",
        "b2b_apply": "5/hour",
        "guest_order": "20/hour",
        "promo_validate": "30/hour",
    },
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'legitorganic'),
        'USER': os.getenv('DB_USER', 'legitorganic_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google OAuth
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

LOG_FILE = os.environ.get(
    'DJANGO_LOG_FILE',
    os.path.join(BASE_DIR, 'django_errors.log')
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
