# Generated by Django 5.2.7 on 2026-06-28 20:18

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_guest_email_order_guest_name_order_guest_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=sales.models.generate_referral_code, max_length=10, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('commission_rate_registration', models.DecimalField(decimal_places=2, default=5.0, help_text='Flat amount in GHS paid when a referred customer registers', max_digits=8)),
                ('commission_rate_first_purchase', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of order total on customer first purchase', max_digits=5)),
                ('commission_rate_repeat_purchase', models.DecimalField(decimal_places=2, default=3.0, help_text='Percentage of order total on repeat purchases', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferredCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rep_form', 'Rep Form'), ('referral_link', 'Referral Link')], max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('converted', 'Converted')], default='registered', max_length=20)),
                ('commission_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_customers', to='sales.salesrep')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration', 'Registration'), ('first_purchase', 'First Purchase'), ('repeat_purchase', 'Repeat Purchase')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='orders.order')),
                ('referred_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.referredcustomer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.salesrep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
