# Generated by Django 5.2.7 on 2026-07-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepPerformance',
            fields=[
            ],
            options={
                'verbose_name': 'Rep Performance',
                'verbose_name_plural': 'Rep Performance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.salesrep',),
        ),
    ]
