# Generated by Django 5.2.7 on 2026-06-07 08:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userrecipe_userrecipeingredient_recipepairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='instruction',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
