# Generated by Django 5.2.7 on 2026-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutritional_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nutritional score out of 100'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video URL for recipe preparation video'),
        ),
    ]
