# Generated by Django 5.2.7 on 2026-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_nutritional_score_recipe_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCombinationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_key', models.CharField(max_length=500, unique=True)),
                ('titles', models.JSONField(default=list)),
                ('note', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
