# Generated by Django 5.2.7 on 2026-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipecombinationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to archive this recipe from the public website.'),
        ),
    ]
