# Generated by Django 5.2.7 on 2026-08-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_publication_state(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.filter(is_published=True).iterator():
        Recipe.objects.filter(pk=recipe.pk).update(
            status='published', published_at=recipe.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        ('recipes', '0006_recipe_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('canonical_name', models.CharField(max_length=200)),
                ('lookup_name', models.CharField(blank=True, help_text='Optional scientific or common name used when searching nutrition sources.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='country',
            field=models.CharField(blank=True, default='Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, default='Ghanaian', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extraction_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='local_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('ready', 'Ready'), ('partial', 'Partial'), ('stale', 'Stale'), ('failed', 'Failed')], default='not_requested', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='review_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('nutrition_pending', 'Nutrition pending'), ('ready', 'Ready'), ('published', 'Published'), ('rejected', 'Rejected')], default='needs_review', max_length=30),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='grams_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='grams_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='grams_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='normalized_ingredient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='normalized_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_match_status',
            field=models.CharField(choices=[('exact', 'Exact'), ('normalized', 'Normalized'), ('usda_verified', 'USDA verified'), ('local_verified', 'Local verified'), ('estimated', 'Estimated'), ('unresolved', 'Unresolved')], default='unresolved', max_length=30),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='preparation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='raw_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published recipes are visible on the public website.'),
        ),
        migrations.CreateModel(
            name='IngredientNutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('source', models.CharField(choices=[('usda', 'USDA FoodData Central'), ('ghanaian_food_composition', 'Ghanaian food composition data'), ('manufacturer', 'Manufacturer'), ('laboratory', 'Laboratory'), ('academic_source', 'Academic source'), ('manual_verified', 'Manual verified'), ('other', 'Other')], max_length=40)),
                ('source_reference', models.TextField()),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('fdc_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('protein_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('carbohydrate_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fat_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('saturated_fat_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fibre_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sugar_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sodium_mg_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cholesterol_mg_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('micronutrients_json', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_nutrition_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['normalized_name', '-verified', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='recipes.ingredientnutritionprofile'),
        ),
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='legitorganic', max_length=30)),
                ('is_complete', models.BooleanField(default=False)),
                ('calculation_warnings', models.JSONField(blank=True, default=list)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fibre_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cholesterol_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('micronutrients_json', models.JSONField(blank=True, default=dict)),
                ('total_recipe_values_json', models.JSONField(blank=True, default=dict)),
                ('per_serving_values_json', models.JSONField(blank=True, default=dict)),
                ('ingredients_hash', models.CharField(max_length=64)),
                ('provider_payload_hash', models.CharField(blank=True, max_length=64)),
                ('provider_response_metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMeasurementConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('source_reference', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measurement_conversions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='recipes.ingredientnutritionprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'unit', 'quantity'), name='unique_profile_measurement_conversion')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('alias', 'Alias'), ('category', 'Category'), ('manual', 'Manual'), ('none', 'No match')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('manually_verified', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_matches', to='products.product')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='recipes.recipeingredient')),
            ],
            options={
                'ordering': ['-manually_verified', '-confidence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recipe_ingredient', 'product'), name='unique_recipe_ingredient_product_match')],
            },
        ),
        migrations.CreateModel(
            name='USDANutritionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('data_type', models.CharField(blank=True, max_length=80)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usda_candidates', to='recipes.recipeingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe_ingredient', 'fdc_id'), name='unique_ingredient_usda_candidate')],
            },
        ),
        migrations.RunPython(preserve_existing_publication_state, migrations.RunPython.noop),
    ]
