# Generated by Django 5.2.7 on 2026-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientalias_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='source_instruction_text',
            field=models.TextField(blank=True),
        ),
    ]
