# Generated by Django 5.2.7 on 2026-08-20 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipestep_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnutritionprofile',
            name='source',
            field=models.CharField(choices=[('wafct_2019', 'FAO/INFOODS WAFCT 2019'), ('usda', 'USDA FoodData Central'), ('fao_infoods', 'Other FAO/INFOODS data'), ('ghana_csir', 'Ghana CSIR food composition data'), ('ghanaian_food_composition', 'Ghanaian food composition data'), ('manufacturer', 'Manufacturer'), ('laboratory', 'Laboratory'), ('academic_source', 'Academic source'), ('manual_verified', 'Manual verified'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='nutrition_match_status',
            field=models.CharField(choices=[('exact', 'Exact'), ('normalized', 'Normalized'), ('wafct_verified', 'WAFCT verified'), ('usda_verified', 'USDA verified'), ('local_verified', 'Local verified'), ('estimated', 'Estimated'), ('unresolved', 'Unresolved')], default='unresolved', max_length=30),
        ),
        migrations.CreateModel(
            name='NutritionSourceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=80)),
                ('publisher', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('citation', models.TextField()),
                ('reuse_terms', models.TextField()),
                ('commercial_permission_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Commercial permission pending'), ('granted', 'Commercial permission granted'), ('denied', 'Commercial permission denied')], default='pending', max_length=20)),
                ('commercial_permission_reference', models.TextField(blank=True)),
                ('workbook_sha256', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_datasets_imported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=80)),
                ('original_food_name', models.CharField(max_length=700)),
                ('food_name_french', models.CharField(blank=True, max_length=700)),
                ('scientific_name', models.CharField(blank=True, max_length=300)),
                ('canonical_name', models.CharField(blank=True, max_length=300)),
                ('preparation_state', models.CharField(blank=True, max_length=300)),
                ('source_identifiers', models.JSONField(blank=True, default=dict)),
                ('nutrient_values', models.JSONField(default=dict)),
                ('quality_indicators', models.JSONField(blank=True, default=dict)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='recipes.nutritionsourcedataset')),
                ('nutrition_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_record', to='recipes.ingredientnutritionprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_nutrition_source_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['original_food_name', 'food_code'],
            },
        ),
        migrations.CreateModel(
            name='RegionalNutritionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_candidates', to='recipes.recipeingredient')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_candidates', to='recipes.nutritionsourcerecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nutritionsourcerecord',
            constraint=models.UniqueConstraint(fields=('dataset', 'food_code'), name='unique_dataset_food_code'),
        ),
        migrations.AddConstraint(
            model_name='regionalnutritioncandidate',
            constraint=models.UniqueConstraint(fields=('recipe_ingredient', 'source_record'), name='unique_ingredient_regional_candidate'),
        ),
    ]
