# Generated by Django 5.2.17 on 2026-09-03 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredientnutritionprofile_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('publisher', 'Recipe publisher'), ('institution', 'Public institution'), ('partner', 'Partner or contributor'), ('other', 'Other')], default='publisher', max_length=30)),
                ('terms_url', models.URLField(blank=True)),
                ('license_name', models.CharField(blank=True, max_length=200)),
                ('attribution_required', models.BooleanField(default=True)),
                ('allows_recipe_reuse', models.BooleanField(default=False)),
                ('allows_images', models.BooleanField(default=False)),
                ('reuse_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('robots_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reuse_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_sources_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_idea', models.CharField(blank=True, max_length=300)),
                ('requested_country', models.CharField(default='Ghana', max_length=100)),
                ('requested_region', models.CharField(blank=True, max_length=100)),
                ('requested_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('ready', 'Ready for review'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('applied', 'Applied to form')], default='started', max_length=20)),
                ('extraction_method', models.CharField(blank=True, choices=[('research_ai', 'Web research and AI'), ('json_ld', 'Schema.org Recipe JSON-LD'), ('ai_fallback', 'AI extraction from source')], max_length=30)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('source_title', models.CharField(blank=True, max_length=300)),
                ('source_author', models.CharField(blank=True, max_length=200)),
                ('source_license', models.CharField(blank=True, max_length=200)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('draft_payload', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_imports', to=settings.AUTH_USER_MODEL)),
                ('duplicate_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_imports', to='recipes.recipe')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='recipes.recipe')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='recipes.recipesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
