# Generated by Django 5.2.7 on 2026-06-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
