# Generated by Django 5.2.7 on 2026-06-12 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['min_order_amount'],
            },
        ),
        migrations.CreateModel(
            name='B2BProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('school', 'School / University'), ('hotel', 'Hotel / Hospitality'), ('catering', 'Catering Company'), ('supermarket', 'Supermarket / Retail'), ('other', 'Other')], max_length=50)),
                ('contact_person', models.CharField(max_length=150)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_address', models.TextField()),
                ('business_registration', models.CharField(blank=True, max_length=100)),
                ('estimated_monthly_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.b2bdiscounttier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2B Profile',
                'verbose_name_plural': 'B2B Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
