# Generated by Django 5.2.7 on 2026-06-12 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_seed_b2b_discount_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
