# Generated by Django 5.2.7 on 2026-08-01 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_b2bprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('delivery_email', models.EmailField(help_text='Personal address used only to deliver the setup link.', max_length=254)),
                ('role', models.CharField(choices=[('Executive Admin', 'Executive Admin'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Sales & Marketing', 'Sales & Marketing'), ('Product Manager', 'Product Manager'), ('Content Team', 'Content Team')], max_length=50)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Delivery failed')], default='pending', editable=False, max_length=20)),
                ('delivery_error', models.CharField(blank=True, editable=False, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('resend_staffinvitation', 'Can resend staff invitation'), ('revoke_staffinvitation', 'Can revoke staff invitation')],
            },
        ),
    ]
