# Generated by Django 5.2.7 on 2026-08-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_staffinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff account',
                'verbose_name_plural': 'Staff accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
