# Generated by Django 5.2.7 on 2026-08-08 07:15

import django.db.models.deletion
from django.db import migrations, models


def create_default_price_list(apps, schema_editor):
    BusinessPriceList = apps.get_model('users', 'BusinessPriceList')
    BusinessPriceList.objects.get_or_create(
        name='Standard business prices',
        defaults={'description': 'Default wholesale catalogue', 'is_default': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        ('users', '0010_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='b2bprofile',
            name='tier',
        ),
        migrations.CreateModel(
            name='BusinessPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_prices', to='products.product')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='users.businesspricelist')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddField(
            model_name='b2bprofile',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='users.businesspricelist'),
        ),
        migrations.RunPython(create_default_price_list, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='B2BDiscountTier',
        ),
        migrations.AddConstraint(
            model_name='businessprice',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='unique_business_product_price'),
        ),
    ]
