# Generated by Django 5.2.17 on 2026-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_b2bprofile_assigned_to_alter_b2bprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bprofile',
            name='registration_status',
            field=models.CharField(choices=[('registered', 'Registered business or organisation'), ('informal', 'Informal / owner-operated business')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='b2bprofile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('school', 'School / University'), ('hotel', 'Hotel / Hospitality'), ('catering', 'Catering Company'), ('supermarket', 'Supermarket / Retail'), ('market_trader', 'Market trader / produce retailer'), ('food_vendor', 'Food vendor / chop bar'), ('other', 'Other'), ('informal_operator', 'Informal / owner-operated business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2bprofile',
            name='verification_document_type',
            field=models.CharField(blank=True, choices=[('orc_certificate', 'ORC registration or incorporation certificate'), ('introductory_letter', 'Official introductory or authorisation letter'), ('ghana_card', 'Ghana Card'), ('drivers_licence', 'Ghanaian driver’s licence'), ('passport', 'Passport'), ('trade_association_letter', 'Trade or market association letter'), ('operating_site_evidence', 'Evidence of operating location')], max_length=30),
        ),
    ]
