# Generated by Django 5.2.17 on 2026-08-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_b2bprofile_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bprofile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('school', 'School / University'), ('hotel', 'Hotel / Hospitality'), ('catering', 'Catering Company'), ('supermarket', 'Supermarket / Retail'), ('market_trader', 'Market trader / produce retailer'), ('food_vendor', 'Food vendor / chop bar'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2bprofile',
            name='legal_structure',
            field=models.CharField(choices=[('business_name', 'Business name / sole proprietor'), ('partnership', 'Partnership'), ('limited_shares', 'Company limited by shares'), ('limited_guarantee', 'Company limited by guarantee / NGO'), ('public_institution', 'Public institution / MDA / MMDA'), ('cooperative', 'Cooperative'), ('foreign_mission', 'Foreign mission / external organisation'), ('other', 'Other'), ('informal_operator', 'Informal / owner-operated business')], default='business_name', max_length=40),
        ),
    ]
